name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  merge_group: { }

concurrency:
  group: pull-request-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Install dependencies
        run: make deps tidy install-test-tools
      - name: Run tests
        id: tests
        shell: bash
        run: make run-tests
      - name: Upload Test Report
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: junit-go-test.xml
          path: junit-go-test.xml
